#!/bin/sh -eu

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

info() {
  printf '      %s\n' "$*" >&2
}

warn() {
  printf 'warning: %s\n' "$*" >&2
}

info "setting up shadow password configuration..."
grpconv
pwconv

info "reinstalling system packages..."
emerge -ekv @system

info "installing additional packages..."
[ -n "${PACKAGES:-}" ] && emerge -kv $PACKAGES
