#!/bin/sh -eu
# Copyright © 2016-2017 Samuel Holland <samuel@sholland.org>
# See LICENSE in the project directory for license terms.
# vim: expandtab:sts=2:sw=2:ts=8:tw=100
#

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

info() {
  printf '      %s\n' "$*" >&2
}

warn() {
  printf 'warning: %s\n' "$*" >&2
}

root=${1:-}
[ -n "$root" ] || die "no root directory given"

info "removing portage cache/config..."
rm -fr --one-file-system "${root}/etc/portage"/*
rm -fr --one-file-system "${root}/var/cache/edb"/*
