#!/bin/sh -eu
# Copyright © 2016-2017 Samuel Holland <samuel@sholland.org>
# See LICENSE in the project directory for license terms.
# vim: expandtab:sts=2:sw=2:ts=8:tw=100
#

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

info() {
  printf '      %s\n' "$*" >&2
}

warn() {
  printf 'warning: %s\n' "$*" >&2
}

root=${1:-}
[ -n "$root" ] || die "no root directory given"

export INSTALL_MASK="/etc/portage charset.alias"

info "copying portage configuration..."
rsync -a /etc/portage/ "${root}/etc/portage/"

info "installing baselayout..."
FEATURES=-buildpkg USE=build emerge --root="$root" baselayout

info "installing system packages..."
emerge --root="$root" -Kv @system

info "updating library paths..."
ldconfig -r "$root" -NX
